builds:
    image: camilstaps/clean:nightly
    script:
        - apt-get update -qq
        - apt-get install -yy build-essential gcc-mingw-w64 zip
        - install_clean.sh clean-base
        - bash mkpkgs.sh
    artifacts:
        paths:
            - "*.tar.gz"
            - "*.zip"
