linux:
    image: gcc:latest
    script:
        - cd src
        - make
        - mkdir CleanSerial
        - mv -v "Clean System Files" {TTY,iTasksTTY}.[id]cl POSIX/Platform.[id]cl CleanSerial
        - tar -cfz CleanSerial-linux64.tar.gz CleanSerial
