test-nightly:
  before_script:
    - install_clean.sh bundle-complete
    - apt-get update -qq
    - apt-get install -y -qq build-essential git coreutils libmariadb-dev libsnappy-dev libsqlite3-dev

    - make -C src/cdeps install

    - git clone https://gitlab.science.ru.nl/clean-compiler-and-rts/compiler tests/linux64/compiler
    - make -j -C tests/linux64/compiler/main/Unix
    - make -j -C tests/linux64/compiler/backendC/CleanCompilerSources -f Makefile.linux64
    - mkdir -p tests/linux64/compiler/backend/Clean\ System\ Files
    - ln -fs ../../backendC/CleanCompilerSources/backend.a tests/linux64/compiler/backend/Clean\ System\ Files/backend_library
  image: "camilstaps/clean:nightly"
  script:
    - COCLPATH=./compiler make -C tests/linux64 run
    - cleantest -r testproperties --options '-IL;Dynamics;-d;src/libraries/OS-Independent;-P;OutputTestEvents;-T;Tests 100000;-T;MaxStringLength 500;-T;Bent;-C;-h;-C;100m;-r' --junit junit.xml
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml
