test:
  before_script:
    - install_clean.sh bundle-complete
    - apt-get update -qq
    - apt-get install -y -qq build-essential git coreutils
    - git clone --recursive https://gitlab.science.ru.nl/clean-and-itasks/clean-test /opt/clean-test
    - make -C /opt/clean-test
  image: "camilstaps/clean:nightly"
  script:
    - make -C tests/linux64 run
    - stdbuf -o0 -e0 /opt/clean-test/makecleantest -IL Dynamics -d src/libraries/OS-Independent -P Quiet -r
